### ISSUE TITLE
Conflict with various-complements-plugin 

### ISSUE THREAD

**Issue by lifesign** [saibotsivad/obsidian-at-people#3]
When using the plugin, I encountered two issues:

1. The plugin conflicts with the various-complements plugin, and the "new person" prompt does not appear.
2. When I click @xx, the new file will appear in the "location for new notes," which in my case is the `Inbox` folder, instead of the location I set in the atPeople plugin configuration, which is `Cards/People/`

**Comment by lifesign** [comment]
issue1 solved. you can add `@` in various-complements this config

![image](https://github.com/saibotsivad/obsidian-at-people/assets/2189610/c1582ff4-e59d-456d-b798-3c6b2d1864ad)

**Comment by saibotsivad** [comment]
Awesome, thanks for documenting this!

**Comment by lifesign** [comment]
> Awesome, thanks for documenting this!

hi, issue2 still exists, should i submit a new issue?

**Comment by saibotsivad** [comment]
Oh hey, missed your second issue there, sorry!

What's probably going on is, unless you set the option for explicit links to true, the inserted link actually looks just like this:

```
Link to [[@Person Name]].
```

If there's a unique file somewhere in Obsidian in a folder it'll go there, but if it doesn't exist and you click on it, it'll create it wherever the link says, which is at the root of the vault.

If you turn on the "Explicit Links" option, the link will look more like this, which will get you the behavior that you're probably expecting:

```
Link to [[People/@Person Name.md|@Person Name]].
```

**Comment by lifesign** [comment]
that's what i need, thx~
