### ISSUE TITLE
Conflict with Tasks plugin

### ISSUE THREAD

**Issue by saibotsivad** [saibotsivad/obsidian-at-people#6]
When you use the [Tasks plugin](https://publish.obsidian.md/tasks/Introduction) with the suggestions, it can block access to this plugin.

When you type this:

```
- [ ] make sure @Ri<CURSOR>
```

What gets suggested is the Tasks plugin suggestions.

**Comment by saibotsivad** [comment]
A hacky solution is to enable this plugin ***first***, wait a second or two for Obsidian to catch up, and then enable the Tasks plugin.

This sets the plugin load order.

Thanks to @claremacrae for finding this solution. Discussion posted here, maybe there's a different solution? https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/2236

**Comment by claremacrae** [comment]
I think if you're happy to close this one, as the workaround is OK, I'm inclined to close the discussion in Tasks too.

**Comment by saibotsivad** [comment]
Yep, just closed it, thanks again!

**Comment by kblattmann** [comment]
This issue was really bothering me. @saibotsivad Perhaps you can mention this fix more prominently in the documentation? Love this plugin!
