### ISSUE TITLE
Console.log leaked into the released version

### ISSUE THREAD

**Issue by dkarter** [saibotsivad/obsidian-at-people#9]
Hi,

Thanks for this plugin! It is very useful to me and I like it more than other options!

I did notice this console log when I opened the developer console:
<img width="584" alt="CleanShot 2023-09-20 at 22 28 40@2x" src="https://github.com/saibotsivad/obsidian-at-people/assets/551858/ac915fdc-590b-41d8-bcbc-3627a63cd0fa">

<img width="622" alt="CleanShot 2023-09-20 at 22 30 23@2x" src="https://github.com/saibotsivad/obsidian-at-people/assets/551858/d366f6ba-0b9c-42d2-87e6-1f89e4c90bb0">

Looking at the code I see that you removed this console log in [7b7f133](https://github.com/saibotsivad/obsidian-at-people/commit/7b7f133c70cbd26ca34a2c683bba156d7004dfc5) but this was not released yet.

**Comment by SkepticMystic** [comment]
+1
